### ISSUE TITLE
Treesitter

### ISSUE THREAD

**Issue by Gako358** [wiltaylor/neovim-flake#4]
I've build my (building) nvim based on your "template" and trying to make sense of things. However treesitter will not work, it install the parsers with :TSInstall but they are not there. How do you link them, or how do you install them to get treesitter highlights working?

**Comment by zoedsoupe** [comment]
Hello, you could llo on how I solve this problem: https://github.com/zoedsoupe/copper/blob/main/lib.nix and https://github.com/zoedsoupe/copper/blob/main/modules/treesitter.nix

**Comment by Gako358** [comment]
Hey, thank you so much for trying to help me.  I tried doing what you have done, but It will not install the parsers, I know I am doing it wrong, if you would be so kind to have a look, i would appreciate it.

https://github.com/Gako358/nvimFlakes/tree/3af5ac1a044a5094248e475eba654cc74feed327

**Comment by wiltaylor** [comment]
Hey,
Sorry for taking so long to get back to you. I have found I have had to run :TSUpdate to get them to install and update every now and then. I kinda wish there was a nicer way to integrate them as part of the flake.

**Comment by Gako358** [comment]
Hey will, there is. I got it working, look at my flake 😊
