### ISSUE TITLE
attribute 'defaultApp.x86_64-linux' should have type 'derivation'

### ISSUE THREAD

**Issue by henrik-ch** [wiltaylor/neovim-flake#5]
I am quite new both to nix and nix flakes and wanted to try out your neovim configuration.

Here the steps to reproduce:

 ```
❯ gh repo clone wiltaylor/neovim-flake
❯ cd neovim-flake
❯ nix run .#
error: attribute 'defaultApp.x86_64-linux' should have type 'derivation'
 ```
I googled for that error message and found:
https://github.com/NixOS/nix/issues/6448 but I am having trouble understanding that thread/issue.

any additional diagnostics that I should include?

```
❯ nix --version
nix (Nix) 2.11.1
```

running nix on ubuntu WSL.

**Comment by wiltaylor** [comment]
Looking at that bug you linked it appears the way apps work has changed so will have to make a change.

You can probably use `nix run github:wiltaylor/neovim-flake#nvim` to get it to work in the meantime though.

**Comment by henrik-ch** [comment]
Thank you very much for taking the time to reply Wil.

You are right, using your command, I get much further, and neovim loads.
There is one error message at startup - please see screenshot below.
I am not sure if that error message is an important one or not.

I am not very far in my nix/flakes journey yet, and I don't understand why there is a difference calling nix run as in your example, versus cloning your repo and doing `nix run .#` ?
My first guess is this page - but nothing mentioned about the github syntax there as far as I can see?
https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-run.html

Do you have any pointers for which part of the documentation to look at to get a handle on that?


![image](https://user-images.githubusercontent.com/569510/210580591-a4bf2b07-bf7e-47b5-b1d0-460c022fa17b.png)

**Comment by wiltaylor** [comment]
Looks like a bunch of stuff broke since I set this up. It was done before neovim migrated over to the lua config files so I am guessing a lot of stuff has changed since then. 

I should probably create something that is a lot easier to work with than this one.

**Comment by henrik-ch** [comment]
Thank you for your reply.
We can close this issue for the time being, up to you. It doesn't seem like a quick fix by the sounds of it.
